### ISSUE TITLE
Update dependencies to use last version of inappwebview

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/libdart#153]
Update

- `graphql`

```
graphql:
    git:
      url: https://github.com/redDwarf03/graphql-flutter.git
      ref: Web_socket_channel_301
      path: packages/graphql
```
